feat: add gopass, migrate data (#3)
* refactor(lib.sh): remove some duplication

* refactor(download-youtube): change formats, supports muxing audio and video files

* misc: copyright

* misc: replace xclip with wl-copy

* feat(gopass): add gopass submodule

* feat(download-youtube): pass -crf to get smaller files, improve output

* misc: new aliases

* misc: remove fatal from fatal msg

* misc: updates to commitlint and vscode

* feat(gopass): add aliases

* misc(rm): gopass submodule

* misc: code review

diff --git a/bin/download-youtube-id b/bin/download-youtube-id
--- a/bin/download-youtube-id
+++ b/bin/download-youtube-id
@@ -1,85 +1,110 @@
 #! /bin/bash
+# Copyright 2024 Raphael Thomazella. All rights reserved.
+# Use of this source code is governed by the BSD-3-Clause
+# license that can be found in the LICENSE file and online
+# at https://opensource.org/license/BSD-3-clause.
 
 set -euo pipefail
 shopt -s globstar
 trap 'err $LINENO' ERR
 
+### vars and functions ###
+
 vid_id=${1:-}
 format=${2:-}
-destination=${3:-}
+title=${3:-}
+current_wd=$(pwd)
+out_dir="$HOME/Desktop"
+out_filename="$title-$vid_id".mp4
 
-audio_only_format=251
-video_audio_720p=22
-desktop=~/Desktop
+declare -rA format_regexps=(
+  ["4k"]="mp4.+3840x2160"
+  ["2k"]="mp4.+2560x1440"
+  ["audio-only"]="opus.+132k 48k" # produces webm extension
+)
 
 usage() {
-  msgln "Usage: $0 <youtube_video_id> <format> <destination>"
+  msgln "Usage: $0 <youtube_video_id> <format> <title>"
   msgln formats:
-  msgln audio only: $audio_only_format
-  msgln video 720p: $video_audio_720p
-  msgln more formats use yt-dlp --list-formats \$vid_id
-  msgln format defaults to video 720p
-  msgln destination defaults to desktop
+
+  for key in "${!format_regexps[@]}"; do
+    msgln "- $key"
+  done
+
+  msgln output will be in "$out_dir"
+  msgln note: youtube video id will be appended to title
 }
 
-if [ -z "$vid_id" ] || [ "$vid_id" == -h ] || [ "$vid_id" == --help ]; then
-  usage
-  fatal "$LINENO" "No video id provided"
-fi
-
-if [ -z "$format" ]; then
-  msgln defaulting to 720p video format
-  format=$video_audio_720p
-fi
-
-if [ -z "$destination" ]; then
-  msgln defaulting destination to desktop
-  destination=$desktop
-fi
-
-temp_dir=$(mktemp -d youtube_dl-XXXXXX -p /tmp)
-current_wd=$(pwd)
-
-msgln using temp "$temp_dir"
-cd "$temp_dir"
-
-# download from youtube
-if ! yt-dlp -f "$format" "$vid_id" --output "%(title)s-%(release_date)s.%(ext)s"; then
-  yt-dlp "$vid_id" --list-formats
-  fatal "$LINENO" "yt-dlp error, formats supported above"
-fi
-
-# sanitize filename
-if ! rename -z -c -S ___ _ -S _-_ - ./*; then
-  fatal "$LINENO" "rename video error"
-fi
-
-if [ "$format" == $audio_only_format ]; then
-  # convert to mp3
-  # we don't know filename but it's the only file in the folder because we used mktemp
-  if ! ffmpeg -i "$temp_dir"/* -codec:a libmp3lame -q:a 0 out.mp3; then
-    fatal "$LINENO" "mp3 ffmpeg error"
+validateInput() {
+  if [ ! "$vid_id" ] || [ "$vid_id" == -h ] || [ "$vid_id" == --help ]; then
+    usage
+    fatal "$LINENO" "no video id"
   fi
 
-  if ! find . -name "*.webm" -exec mv out.mp3 {}.mp3 \;; then
-    fatal "$LINENO" "mp3 find error"
+  if [ ! "$format" ]; then
+    usage
+    fatal "$LINENO" "no format"
   fi
 
-  if ! rename -S .webm.mp3 .mp3 ./*; then
-    fatal "$LINENO" "mp3 rename webm to mp3 error"
+  if [ ! "$title" ]; then
+    usage
+    fatal "$LINENO" "no title"
   fi
+}
 
-  if ! mv ./*.mp3 ~/Desktop; then
-    fatal "$LINENO" "mp3 mv error"
+prepareTemp() {
+  local temp
+  temp=$(mktemp -d youtube_dl-XXXXXX -p /tmp)
+
+  msgln using temp "$temp"
+  cd "$temp"
+}
+
+download() {
+  local format_line fmt="$1"
+  format_line=$(grep -Eie "${format_regexps[$fmt]}" < <(yt-dlp "$vid_id" --list-formats))
+  read -rs format_id _ <<<"$format_line"
+
+  if ! yt-dlp -f "$format_id" "$vid_id" --output "%(title)s-%(release_date)s.%(ext)s"; then
+    yt-dlp "$vid_id" --list-formats 2>/dev/null
+    fatal "$LINENO" "yt-dlp error, formats supported above"
   fi
+}
 
-  exit 0
+convertMP3() {
+  ffmpeg -i ./* -codec:a libmp3lame -q:a 0 out.mp3
+  find . -name "*.webm" -exec mv out.mp3 {}.mp3 \;
+  rename --subst-all .webm.mp3 .mp3 ./*
+}
+
+mux() {
+  local name=$1
+  ffmpeg -i ./*.mp4 -i ./*.webm -crf 26 -ac 2 "$name"
+}
+
+move() {
+  local name=$1
+  mv "$name" "$out_dir"
+}
+
+cleanup() {
+  cd "$current_wd"
+}
+
+### script ###
+
+validateInput
+prepareTemp
+
+download "$format"
+
+# video formats have no audio, download audio then mux
+if [ "$format" != "audio-only" ]; then
+  download audio-only
+  mux "$out_filename"
+else
+  convertMP3
 fi
 
-if ! mv ./* "$destination"; then
-  fatal "$LINENO" "mv error"
-fi
-
-cd "$current_wd"
-
-msgln "done"
+move "$out_filename"
+cleanup
