refactor: pacu & misc aliases, systemd, functions (#13)
* feat(pacu): prompt to kexec into new kernel

* misc: remove debug echo

* misc(systemd): adjust hibernate delay to 12h

* misc(aliases): add some mpv flags

* misc(systemd): increase hibernation delay

* feat(pacu): sudo_refresh background func

* refactor(pacu): remove node downgrade steps

* misc(functions): keep some packages on pacman orphan script

* feat(pacu): no stop sddm and no reboot, update message

* feat(etc/systemd): increase hibernate delay

* docs(env): add Get docs

* fix(bin/interface-hook-pre-commit): boot hook linux only

* docs(pacu): document some funcs

* misc(systemd/sleep.conf.d): update hibernate delay

diff --git a/bin/pacu b/bin/pacu
--- a/bin/pacu
+++ b/bin/pacu
@@ -13,10 +13,17 @@ trap 'err $LINENO' ERR
 
 ### vars and functions ###
 
+sudo_refresh() {
+  while true; do
+    sudo -v
+    sleep 240 # 4 minutes
+  done
+}
+
 logout() {
   local response
 
-  msgln "please logout and switch to a console. All done? (timeout 10s) [y/N]"
+  msgln "please logout and switch to a console. All done? (timeout 10s) [y/N] (10s fatal timeout)"
   read -t 10 -r response
   if [ "$response" != "y" ] && [ "$response" != "Y" ]; then
     fatal $LINENO logout required
@@ -26,8 +33,8 @@ logout() {
 do_snapshot() {
   local response
 
-  msgln "start a new @root snapshot? Sudo is necessary (timeout 10s) [y/N]"
-  read -t 10 -r response
+  msgln "start a new @root snapshot? Sudo is necessary (timeout 10s) [y/N] (10s timeout)"
+  read -t 10 -r response || true
   if [ "$response" == "y" ] || [ "$response" == "Y" ]; then
     sudo "$HOME/bin/snapshot"
   fi
@@ -36,6 +43,7 @@ do_snapshot() {
 services() {
   local cmd="$1" service
 
+  msgln "$cmd-ing services, sudo is necessary"
   for service in "${@:2}"; do
     sudo systemctl "$cmd" "$service".service
     log $LINENO "$cmd $service"
@@ -103,24 +111,19 @@ postgres_up() {
 }
 
 system_up() {
-  local lts_name
-  # use LTS node, the one before the latest LTS
-  read -rs _ _ lts_name _ < <(nvm list --no-colors | grep lts | tail -2 | head -1)
-  # Some software only builds from AUR in old node versions
   # we start by updating NVM itself
   command cd "$NVM_DIR" && git pull
 
   # update node
   nvm install node
-  # temporarily downgrade the default node in nvm
-  log $LINENO "using node $lts_name for upgrade..."
-  nvm install "$lts_name" >/dev/null
   # after install NVM sets the installed node as the one in use
-  LTS_VER="$(node -v)"
-  nvm alias default "$LTS_VER" >/dev/null
+  nvm alias default "$(node -v)" >/dev/null
 
   # fix some install errors
   chmod -R u+w,u+r "$HOME/.cache/yay"
+
+  # keep the sudo timestamp alive across long compiles from AUR
+  sudo_refresh &
 
   # update arch pkgs first to avoid errors
   yay --sync --refresh --needed --noconfirm archlinux-appstream-data archlinux-keyring
@@ -128,7 +131,6 @@ system_up() {
   yay --sync linux linux-api-headers linux-firmware linux-headers --needed --noconfirm
   # update everything but linux from repositories
   yay --repo --sync --sysupgrade --ignore linux,linux-api-headers,linux-firmware,linux-headers --needed --noconfirm
-  sudo -v
 
   # update everything but linux from AUR
   if ! yay --aur --sync --sysupgrade --ignore linux,linux-api-headers,linux-firmware,linux-headers --needed --noconfirm; then
@@ -137,11 +139,7 @@ system_up() {
 }
 
 reinstall_global_npm() {
-  local old_node="$1" packages=("${@:2}") name version
-
-  if [ "$old_node" == "$(node -v)" ]; then
-    return
-  fi
+  local packages=("${@:1}") name version
 
   if ((${#packages[@]} % 2 != 0)); then
     fatal $LINENO "expected an even number of packages and versions"
@@ -163,8 +161,6 @@ reinstall_global_npm() {
 
 cleanup() {
   local pg_major="$1"
-  # restore node to latest
-  nvm alias default node 1>/dev/null
 
   if [ "$pg_major" ]; then
     # make sure postgresql is restarted successfully before attempting removal
@@ -193,29 +189,53 @@ btrfs_check() {
   done
 }
 
-finally() {
-  msgln "success, you may want to reboot.
-    consider booting to flashdrive and running on / using 'btrfs check --check-data-csum /dev/disk/by-label/Archlinux'
+success_message() {
+  msgln "success; consider booting to flashdrive and running 'btrfs check --check-data-csum /dev/disk/by-label/Archlinux'
     if btrfs checks were started, you can monitor them with pgrep -f 'btrfs check'.
-    sddm was not restarted, you can do so now to go back to GUI."
+    You should probably logout and restart SDDM.
+    "
+}
+
+# todo: currently doesn't tell if the kernel was updated or not and always prompts
+kexec_prompt() {
+  local response base_name=vmlinuz-linux suffix="${1:-}"
+  local kernel_file="/boot/$base_name$suffix" initrd_file="/boot/initramfs-linux$suffix.img"
+
+  if ! stat "$kernel_file" >/dev/null 2>&1; then
+    warn $LINENO "kernel file not found: $kernel_file"
+    return
+  fi
+
+  if ! stat "$initrd_file" >/dev/null 2>&1; then
+    warn $LINENO "initramfs file not found: $initrd_file"
+    return
+  fi
+
+  msgln "load new kernel and switch to it? Beware: btrfs checks may be running. This will be equivalent to a fast reboot. [y/N] (10s timeout)"
+  msgln "kernel: $kernel_file"
+  read -t 10 -r response || true
+  if [ "$response" == "y" ] || [ "$response" == "Y" ]; then
+    sudo kexec -l "$kernel_file" --initrd="$initrd_file" --reuse-cmdline
+    sudo kexec -e
+  fi
 }
 
 ### script ###
 
 logout
 do_snapshot
-services stop sddm postgresql
+services stop postgresql
 
 btrfs_check Data2TB Data4TB
 pg_update=$(postgres_up)
-old_node=$(node -v)
 
 # shellcheck source=/dev/null
 source "$NVM_DIR/nvm.sh"
 
 system_up
-reinstall_global_npm "$old_node" cspell cspell@latest prettier prettier@latest commitlint @commitlint/cli@latest commitlint/config-conventional @commitlint/config-conventional@latest
+reinstall_global_npm cspell cspell@latest prettier prettier@latest commitlint @commitlint/cli@latest commitlint/config-conventional @commitlint/config-conventional@latest
 services start postgresql
 
 cleanup "$pg_update"
-finally
+kexec_prompt -neptune-65
+success_message
