fix(bin/pacu): cleanup backgrounded processes

diff --git a/bin/pacu b/bin/pacu
--- a/bin/pacu
+++ b/bin/pacu
@@ -13,6 +13,8 @@ trap 'err $LINENO' ERR
 
 ### vars and functions ###
 
+cleanup_processes=()
+
 sudo_refresh() {
   while true; do
     sudo -v
@@ -124,6 +126,7 @@ system_up() {
 
   # keep the sudo timestamp alive across long compiles from AUR
   sudo_refresh &
+  cleanup_processes+=($!)
 
   # update arch pkgs first to avoid errors
   yay --sync --refresh --needed --noconfirm archlinux-appstream-data archlinux-keyring
@@ -218,6 +221,16 @@ kexec_prompt() {
     sudo kexec -l "$kernel_file" --initrd="$initrd_file" --reuse-cmdline
     sudo kexec -e
   fi
+}
+
+cleanup_backgrounded_processes() {
+  for pid in "${cleanup_processes[@]}"; do
+    if ps -p "$pid" >/dev/null; then
+      if ! kill -HUP "$pid"; then
+        warn $LINENO "failed to hangup process $pid"
+      fi
+    fi
+  done
 }
 
 ### script ###
